### ISSUE TITLE
Not work in m1 mac

### ISSUE THREAD

**Issue by wanfuuyu** [mmisono/try-bpftrace-in-mac#1]
Not compatible with m1 mac

![image](https://user-images.githubusercontent.com/8027958/145950182-7983206b-9d8b-45df-84a2-09ae1babd337.png)

**Comment by mmisono** [comment]
For now, only x86-64 binaries are available at https://github.com/iovisor/bpftrace/releases/, where Dockerfile fetches a bpftrace binary. You need to compile bpftrace from source to run bpftrace on a VM on M1 Mac,

**Comment by wanfuuyu** [comment]
I got this, `apt install bpftrace` works fine  😅
